pluginManagement {
    repositories {
        maven {
            url = uri('https://maven-central.storage-download.googleapis.com/maven2/')
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        maven {
            url = uri('https://maven-central.storage-download.googleapis.com/maven2/')
        }
        mavenCentral()
    }
}

rootProject.name = 'orc-carbon-bench'
